site_name: AntakIA. AI explained.

site_url: https://doc.antakia.ai/

theme: material

markdown_extensions:
  - admonition
  - attr_list

plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py 
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    enable_inventory: true
    handlers:
      python:
        paths: [src]


nav:
- Home: index.md
- Getting started: getting_started.md
- Regional explainability: regional_explain.md
- Tutorials: tutorials.md
# defer to gen-files + literate-nav
- Code Reference: reference/  
- About: about.md
- Credits: credits.md