site_name: AntakIA - Read the Docs

site_url: https://ai-vidence.com/documentation-antakia/

nav:
  - Home: index.md
  - Getting Started: getting-started.md
<<<<<<< HEAD
  - User Guide: usage.md
  - API Reference:
      - Documentation: documentation/index.md
=======
  - Usage: usage.md
  - Documentation:
      - About the doc: documentation/index.md
>>>>>>> d52101bce3abd5085f3ea47a4d5e1b95209494f0
      - Xplainer: documentation/xplainer.md
      - Utils: documentation/utils.md
  - About: about.md

theme:
  name: material
  palette:
    primary: white
  logo: img/logo_antakia_transp.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.path

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            show_source: false
            show_bases: false

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
<<<<<<< HEAD

repo_url: https://github.com/AI-vidence/antakia
repo_name: ai-vidence/antakia
=======
>>>>>>> d52101bce3abd5085f3ea47a4d5e1b95209494f0
