[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "antakia"
version = "0.1"
authors = [
    { name = "Antoine EDY", email = "antoineedy@outlook.fr" },
    { name = "Laurent MICHEL", email = "laurent@ai-vidence.com" },
    { name = "David CORTÉS", email = "david@ai-vidence.com" },
]
description = "AI made Xplainable"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = [
    "XAI",
    "explainability",
    "AI",
    "ML",
    "machine learning",
    "artificial intelligence",
]
dynamic = ["dependencies"]



[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
