import os

DEFAULT_EXPLANATION_METHOD = os.environ.get('DEFAULT_EXPLANATION_METHOD', 1)
DEFAULT_VS_DIMENSION = os.environ.get('DEFAULT_VS_DIMENSION', 2)
DEFAULT_ES_DIMENSION = os.environ.get('DEFAULT_ES_DIMENSION', 2)
DEFAULT_VS_PROJECTION = os.environ.get('DEFAULT_VS_PROJECTION', 4)
DEFAULT_ES_PROJECTION = os.environ.get('DEFAULT_ES_PROJECTION', 4)

INIT_FIG_WIDTH = os.environ.get('INIT_FIG_WIDTH', 1800)

# Rule format
USE_INTERVALS_FOR_RULES = os.environ.get('USE_INTERVALS_FOR_RULES', 'True') == 'True'


SHOW_LOG_MODULE_WIDGET = os.environ.get('SHOW_LOG_MODULE_WIDGET', 'False') == 'True'
