DEFAULT_EXPLANATION_METHOD = 1
DEFAULT_VS_DIMENSION = DEFAULT_ES_DIMENSION = 2
DEFAULT_VS_PROJECTION = DEFAULT_ES_PROJECTION = 4

INIT_FIG_WIDTH = 1800

# Rule format
USE_INTERVALS_FOR_RULES = True

SHOW_LOG_MODULE_WIDGET = True
