name: GitlabSync

on:
  - push
  - delete
  - workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        # Such as https://github.com/wangchucheng/git-repo-sync.git
        # target-url: ${{ secrets.TARGET_URL }}
        target-url: https://code.ai-vidence.com/ai-vidence/antakia
        # Such as wangchucheng
        # target-username: ${{ secrets.TARGET_USERNAME }}
        target-username: laurent
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
        # target-token: ${{ secrets.TARGET_TOKEN }}
        target-token: glpat-eT-Uy3JHnueSDsvubey5
