name: Lint with pylint

on:
  release:
    types: [published]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        id: git-co
        uses: actions/checkout@v1
      - name: setup python
        id: python
        uses: actions/setup-python@v1
      - name: setup poetry
        id: poetry
        uses: knowsuchagency/poetry-install@v1
        env:
          POETRY_VIRTUALENVS_CREATE: true
      - name: lint code
        id: lint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
            
          
