name: Lint with pylint

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

permissions:
  contents: read

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install antakia and pylint
        run: |
          pip install "antakia==0.5.1" pylint
      - name: Lint installed package
        run: pylint src/antakia --disable=C,R || true
