name: Run pytest

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: astral-sh/setup-uv@v5
      - name: Install and test
        run: |
          uv pip install --system "antakia==0.5.1" pytest pytest-cov mock
          python -m pytest --cov=antakia --cov-report term-missing tests
