name: Run pytest

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: bash .github/ci/install-deps.sh
      - name: Install test tools
        run: pip install mock pytest pytest-cov
      - name: Run pytest
        run: python -m pytest --cov=antakia --cov-report term-missing tests
