name: Format with yapf

on:
  pull_request:
    branches: [main, dev]

permissions:
  contents: read

jobs:
  yapf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Check yapf formatting
        run: |
          pip install yapf
          yapf --diff --recursive --style pep8 src tests
